### ISSUE TITLE
how to build in vs2015?

### ISSUE THREAD

**Issue by qicosmos** [pferdinand/libpqmxx#1]
i want to use your libray, howerver i can't find the vs2015 project.

**Comment by pferdinand** [comment]
Compiling under Windows is next on my list. Sorry it's not yet available...

**Comment by qicosmos** [comment]
I have run your project in vs2015, but i found some bugs.

**Comment by qicosmos** [comment]
conn.execute("select * from student where age>$1 and name = $2", 10, 'tom');
the result status is fatal error, why?

**Comment by pferdinand** [comment]
Hi qicosmos, 

I've just committed the release 1.0.1 compatible with Windows and fix your issue.
