### ISSUE TITLE
does not surpport int/float/double array.

### ISSUE THREAD

**Issue by qicosmos** [pferdinand/libpqmxx#4]
hi, i can't find the method which is used to get int/float/double array, could you surpport array?

**Comment by pferdinand** [comment]
I have no plan to support it soon. Feel free to submit a pull request.

**Comment by qicosmos** [comment]
OK，i will pull request for array.

**Comment by pferdinand** [comment]
Actually I looked at it. It doesn't look to complicated to support arrays if I refactor the code a little bit. I will try to release it this week.

**Comment by qicosmos** [comment]
yes it is. thanks.

**Comment by pferdinand** [comment]
Arrays are now supported since 1.1 (007dfc94b844ef68a81c37415c683609d75a8d1c)

**Comment by qicosmos** [comment]
@pferdinand greate!
